resources:
  - kind: repository
    selector:
      query: "true" # J  Q bo o lean query. If eva lua ted to fall se - sk ip sy nc I n g t he e o  bj  e c t.
    port:
      entity:
        mappings:
          identifier: ".name" # T he E not ity ident ify ier will be the rep o s it ory n a me.
          title: '"global"'
          blueprint: '"repository"'
          properties:
            readme: file://README.md # fe tchi ng the READ ME.md file that is within t he root folder of the rep osito ry and ingest ing its contents as a markdown property
            url: .html_url
            defaultBranch: .default_branch
  - kind: pull-request
    selector:
      query: "true" # J Q boolean query. If evaluated to false - skip syncing the object.
    port:
      entity:
        mappings:
          identifier: ".head.repo.name + (.id|tostring)" # The Entity identifier will be the repository name + the pull request ID.
          title: ".title"
          blueprint: '"pullRequest"'
          properties:
            creator: ".user.login"
            assignees: "[.assignees[].login]"
            reviewers: "[.requested_reviewers[].login]"
            status: ".status" # merged, closed, opened
            closedAt: ".closed_at"
            updatedAt: ".updated_at"
            mergedAt: ".merged_at"
            prNumber: ".id"
            link: ".html_url"
          relations:
            repository: .head.repo.name
